# 端口
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        # 打开所有的监控点
        include: "*"
      # 自定义监控路径 monitor
      # 默认值：http://localhost:8016/actuator/*
      # 配置后：http://localhost:8016/monitor/*
      base-path: /monitor
  endpoint:
    health:
      show-details: always
    shutdown:
      # 通过指定接口关闭 SpringBoot
      enabled: true
  # 可以自定义端口
  # server:
  #   port: 8089

# 描述项目基础信息
info:
  app:
    name: mySringBoot
    port: 8080
    version: 1.0.0
    author: libbing

spring:
# mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/redis_test?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: THEO1126
  application:
    # 应用名称
    name: mySpringBoot
# 资源
  mvc:
#    view:
#      suffix: .html
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/templates/,classpath:/static/,classpath:/static/js/

  data:
#    redis
    redis:
      host: 127.0.0.1
      password:
      port: 6379
      timeout: 0
      jedis:
        pool:
          max-active: 100
          max-idle: 10
          max-wait: 100000

#  thymeleaf:
#    cache: false
#    prefix: classpath:/static/
#    suffix: .js


# mybatis 加载 bean和 xml ，映射路径配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.edu.guet.bean
  configuration:
    map-underscore-to-camel-case: true
#  configLocation: classpath:mybatis-config.xml


# 日志输出
logging:
  level:
    cn.edu.guet.springbootdemo.mapper: DEBUG
  file:
    name: D:/program/LanqiaoWeb/mySpringBoot/boot.log
