# 端口
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        # 打开所有的监控点
        include: "*"
      # 自定义监控路径 monitor
      # 默认值：http://localhost:8016/actuator/*
      # 配置后：http://localhost:8016/monitor/*
      base-path: /monitor
  endpoint:
    health:
      show-details: always
    shutdown:
      # 通过指定接口关闭 SpringBoot
      enabled: true
  # 可以自定义端口
  # server:
  #   port: 8089

# 描述项目基础信息
info:
  app:
    name: node16-boot-actuator
    port: 8016
    version: 1.0.0
    author: cicada


spring:
# mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/redis_test?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: THEO1126
  application:
    # 应用名称
    name: mySpringBoot
# 资源
  web:
    resources:
      static-locations: classpath:/templates/,classpath:/static/
  mvc:
    view:
      suffix: .html

# mybatis 加载bean和 xml
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.edu.guet.bean

logging:
  level:
    cn.edu.guet.springbootdemo.mapper: DEBUG
